"""PDF report generator using reportlab.

Generates branded weekly and monthly marketing performance PDFs.
ShiftOneZero Marketing Platform
"""

import io
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)

logger = logging.getLogger(__name__)

# Brand colours
NAVY = colors.HexColor("#0A1A28")
ACCENT = colors.HexColor("#B8FF00")
BLUE = colors.HexColor("#0057A8")
LIGHT_GRAY = colors.HexColor("#F3F4F6")
MEDIUM_GRAY = colors.HexColor("#9CA3AF")

PAGE_W, PAGE_H = A4


def _styles():
    """Build custom paragraph styles."""
    base = getSampleStyleSheet()
    base.add(ParagraphStyle(
        "Title_Custom", parent=base["Title"],
        fontName="Helvetica-Bold", fontSize=20, textColor=NAVY,
        spaceAfter=6,
    ))
    base.add(ParagraphStyle(
        "Subtitle", parent=base["Normal"],
        fontName="Helvetica", fontSize=11, textColor=MEDIUM_GRAY,
        spaceAfter=12,
    ))
    base.add(ParagraphStyle(
        "SectionHead", parent=base["Heading2"],
        fontName="Helvetica-Bold", fontSize=13, textColor=BLUE,
        spaceBefore=16, spaceAfter=8,
    ))
    base.add(ParagraphStyle(
        "BodyText_Custom", parent=base["Normal"],
        fontName="Helvetica", fontSize=10, leading=14,
        textColor=NAVY, spaceAfter=6,
    ))
    base.add(ParagraphStyle(
        "SmallGray", parent=base["Normal"],
        fontName="Helvetica", fontSize=8, textColor=MEDIUM_GRAY,
    ))
    return base


def _metric_table(data: list[list], col_widths=None):
    """Create a styled metric table."""
    t = Table(data, colWidths=col_widths, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("GRID", (0, 0), (-1, -1), 0.5, MEDIUM_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
    ]))
    return t


def _kpi_row(styles, items: list[tuple[str, str]]):
    """Create a horizontal KPI summary row as a table."""
    header = [Paragraph(f"<b>{label}</b>", styles["SmallGray"]) for label, _ in items]
    values = [Paragraph(f"<b>{value}</b>", styles["BodyText_Custom"]) for _, value in items]
    t = Table([header, values], colWidths=[120] * len(items), hAlign="LEFT")
    t.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(MEDIUM_GRAY)
    canvas.drawString(
        20 * mm, 10 * mm,
        f"Generated by ShiftOneZero Marketing Platform — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
    )
    canvas.drawRightString(PAGE_W - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _fmt(n, prefix="", suffix="") -> str:
    if isinstance(n, float):
        return f"{prefix}{n:,.2f}{suffix}"
    if isinstance(n, int):
        return f"{prefix}{n:,}{suffix}"
    return f"{prefix}{n}{suffix}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_weekly_pdf(report_data: dict) -> bytes:
    """Render a weekly report dict to PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )
    s = _styles()
    story = []

    period = report_data.get("period", {})
    org = report_data.get("organic_performance", {})
    paid = report_data.get("paid_performance", {})
    sent = report_data.get("sentiment_overview", {})
    recs = report_data.get("ai_recommendations", [])

    # Header
    story.append(Paragraph("SHIFTONEZERO MARKETING", s["Title_Custom"]))
    story.append(Paragraph(
        f"Tjedni marketinski izvještaj — {period.get('start', '')[:10]} do {period.get('end', '')[:10]}",
        s["Subtitle"],
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=12))

    # KPI summary
    story.append(Paragraph("Pregled", s["SectionHead"]))
    story.append(_kpi_row(s, [
        ("Objave", _fmt(org.get("total_posts", 0))),
        ("Prikazivanja", _fmt(org.get("total_impressions", 0))),
        ("Angažman", f"{org.get('avg_engagement_rate', 0):.1f}%"),
        ("Potrošnja", _fmt(paid.get("total_spend", 0), prefix="€")),
        ("ROAS", f"{paid.get('weighted_roas', 0):.1f}x"),
    ]))
    story.append(Spacer(1, 10))

    # Organic
    story.append(Paragraph("Organski performans", s["SectionHead"]))
    top_posts = org.get("top_posts", [])
    if top_posts:
        rows = [["#", "Naslov", "Platforma", "Angažman", "Prikazivanja"]]
        for i, p in enumerate(top_posts[:5], 1):
            rows.append([
                str(i), p.get("title", "")[:40],
                p.get("platform", ""), f"{p.get('engagement_rate', 0):.1f}%",
                _fmt(p.get("impressions", 0)),
            ])
        story.append(_metric_table(rows, col_widths=[20, 180, 70, 60, 80]))
    story.append(Spacer(1, 10))

    # Paid
    story.append(Paragraph("Plaćeni performans", s["SectionHead"]))
    top_ads = paid.get("top_ads", [])
    if top_ads:
        rows = [["#", "Kampanja", "Platforma", "ROAS", "Potrošnja", "Konverzije"]]
        for i, a in enumerate(top_ads[:5], 1):
            rows.append([
                str(i), a.get("campaign", "")[:35],
                a.get("platform", ""), f"{a.get('roas', 0):.1f}x",
                _fmt(a.get("spend", 0), prefix="€"), _fmt(a.get("conversions", 0)),
            ])
        story.append(_metric_table(rows, col_widths=[20, 150, 60, 50, 70, 60]))
    story.append(Spacer(1, 10))

    # Sentiment
    story.append(Paragraph("Sentiment", s["SectionHead"]))
    story.append(_kpi_row(s, [
        ("Pozitivno", f"{sent.get('positive_pct', 0):.0f}%"),
        ("Neutralno", f"{sent.get('neutral_pct', 0):.0f}%"),
        ("Negativno", f"{sent.get('negative_pct', 0):.0f}%"),
        ("Trend", sent.get("sentiment_trend", "—")),
    ]))
    story.append(Spacer(1, 10))

    # AI Recommendations
    if recs:
        story.append(Paragraph("AI preporuke", s["SectionHead"]))
        for i, rec in enumerate(recs, 1):
            story.append(Paragraph(
                f"<b>{i}. [{rec.get('priority', '').upper()}] {rec.get('title', '')}</b>",
                s["BodyText_Custom"],
            ))
            story.append(Paragraph(rec.get("recommendation", ""), s["BodyText_Custom"]))
            story.append(Spacer(1, 4))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def generate_monthly_pdf(report_data: dict) -> bytes:
    """Render a monthly report dict to PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )
    s = _styles()
    story = []

    period = report_data.get("period", {})
    summary = report_data.get("executive_summary", {})
    org = report_data.get("organic", {})
    paid = report_data.get("paid", {})
    sent = report_data.get("sentiment", {})
    market = report_data.get("market_position", {})

    # Header
    story.append(Paragraph("SHIFTONEZERO MARKETING", s["Title_Custom"]))
    story.append(Paragraph(
        f"Mjesečni marketinški izvještaj — {period.get('month', '')}/"
        f"{period.get('year', '')}",
        s["Subtitle"],
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=12))

    # Executive summary
    story.append(Paragraph("Izvršni sažetak", s["SectionHead"]))
    if summary.get("headline"):
        story.append(Paragraph(f"<i>{summary['headline']}</i>", s["BodyText_Custom"]))
    story.append(_kpi_row(s, [
        ("Doseg", _fmt(summary.get("total_reach", 0))),
        ("Angažman", _fmt(summary.get("total_engagement", 0))),
        ("Potrošnja", _fmt(summary.get("total_spend", 0), prefix="€")),
        ("Prihod", _fmt(summary.get("total_revenue", 0), prefix="€")),
        ("Profit", _fmt(summary.get("profit", 0), prefix="€")),
    ]))
    story.append(Spacer(1, 10))

    # Organic
    story.append(Paragraph("Organski performans", s["SectionHead"]))
    story.append(_kpi_row(s, [
        ("Objave", _fmt(org.get("total_posts", 0))),
        ("Prikazivanja", _fmt(org.get("total_impressions", 0))),
        ("Doseg", _fmt(org.get("total_reach", 0))),
        ("Angažman", f"{org.get('avg_engagement_rate', 0):.1f}%"),
    ]))

    followers = org.get("followers_gained", {})
    if followers:
        rows = [["Platforma", "Novi pratitelji"]]
        for platform, count in followers.items():
            rows.append([platform.capitalize(), _fmt(count, prefix="+")])
        story.append(Spacer(1, 6))
        story.append(_metric_table(rows, col_widths=[120, 100]))
    story.append(Spacer(1, 10))

    # Paid
    story.append(Paragraph("Plaćeni performans", s["SectionHead"]))
    story.append(_kpi_row(s, [
        ("Kampanje", _fmt(paid.get("total_campaigns", 0))),
        ("Potrošnja", _fmt(paid.get("total_spend", 0), prefix="€")),
        ("Konverzije", _fmt(paid.get("total_conversions", 0))),
        ("ROAS", f"{paid.get('weighted_roas', 0):.1f}x"),
        ("CTR", f"{paid.get('avg_ctr', 0):.1f}%"),
    ]))
    story.append(Spacer(1, 10))

    # Sentiment
    story.append(Paragraph("Sentiment", s["SectionHead"]))
    story.append(_kpi_row(s, [
        ("Pozitivno", f"{sent.get('positive_pct', 0):.0f}%"),
        ("Neutralno", f"{sent.get('neutral_pct', 0):.0f}%"),
        ("Negativno", f"{sent.get('negative_pct', 0):.0f}%"),
        ("NPS", _fmt(sent.get("nps_estimate", 0))),
    ]))
    story.append(Spacer(1, 10))

    # Market position
    if market:
        story.append(Paragraph("Tržišna pozicija", s["SectionHead"]))
        story.append(_kpi_row(s, [
            ("Engagement indeks", f"{market.get('engagement_index', 0):.2f}"),
            ("Liga pozicija", f"#{market.get('position_in_league', 0)}"),
            ("Udio pratitelja", f"{market.get('follower_share_pct', 0):.1f}%"),
            ("Udio glasova", f"{market.get('brand_mention_share', 0):.1f}%"),
        ]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
