from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any


class BaseIntegrationClient(ABC):
    """Base class for all API integration clients."""

    is_mock: bool = False

    @abstractmethod
    async def health_check(self) -> dict:
        """Check if the integration is healthy."""
        ...


class MetaClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_page_insights(self, page_id: str, metrics: list[str], period: str = "day") -> dict: ...
    @abstractmethod
    async def get_instagram_insights(self, account_id: str, metrics: list[str]) -> dict: ...
    @abstractmethod
    async def get_instagram_media(self, account_id: str, limit: int = 25) -> list[dict]: ...
    @abstractmethod
    async def get_audience_demographics(self, account_id: str) -> dict: ...
    @abstractmethod
    async def create_campaign(self, ad_account_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def create_ad_set(self, ad_account_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def create_ad(self, ad_account_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def get_ad_insights(self, ad_id: str, fields: list[str]) -> dict: ...
    @abstractmethod
    async def pause_ad(self, ad_id: str) -> dict: ...
    @abstractmethod
    async def update_ad_budget(self, ad_set_id: str, new_budget: float) -> dict: ...


class TikTokClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_account_info(self) -> dict: ...
    @abstractmethod
    async def get_video_list(self, limit: int = 20) -> list[dict]: ...
    @abstractmethod
    async def get_video_insights(self, video_id: str) -> dict: ...
    @abstractmethod
    async def create_campaign(self, data: dict) -> dict: ...
    @abstractmethod
    async def create_ad_group(self, data: dict) -> dict: ...
    @abstractmethod
    async def create_ad(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_ad_insights(self, ad_id: str) -> dict: ...


class YouTubeClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_channel_stats(self, channel_id: str) -> dict: ...
    @abstractmethod
    async def get_recent_videos(self, channel_id: str, limit: int = 10) -> list[dict]: ...
    @abstractmethod
    async def get_video_stats(self, video_id: str) -> dict: ...
    @abstractmethod
    async def get_audience_demographics(self, channel_id: str) -> dict: ...


class GA4ClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_report(self, property_id: str, metrics: list[str], dimensions: list[str], date_range: dict) -> dict: ...
    @abstractmethod
    async def get_realtime_report(self, property_id: str) -> dict: ...
    @abstractmethod
    async def get_audience_overview(self, property_id: str, date_range: dict) -> dict: ...


class SportsDataClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_leagues_by_country(self, country_code: str) -> list[dict]: ...
    @abstractmethod
    async def get_events_by_league(self, league_id: str, season: str) -> list[dict]: ...
    @abstractmethod
    async def get_team_info(self, team_name: str) -> dict: ...
    @abstractmethod
    async def get_upcoming_events(self, team_id: str) -> list[dict]: ...


class ClaudeClientBase(BaseIntegrationClient):
    @abstractmethod
    async def generate_content_plan(self, context: dict) -> dict: ...
    @abstractmethod
    async def generate_post_copy(self, brief: dict) -> dict: ...
    @abstractmethod
    async def generate_ab_variants(self, base_copy: str, num_variants: int = 3) -> list[dict]: ...
    @abstractmethod
    async def analyze_sentiment(self, texts: list[str]) -> list[dict]: ...
    @abstractmethod
    async def generate_report_summary(self, data: dict) -> str: ...
    @abstractmethod
    async def generate_strategy_recommendation(self, performance_data: dict) -> dict: ...


class BufferClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_profiles(self) -> list[dict]: ...
    @abstractmethod
    async def create_post(self, profile_ids: list[str], text: str, media: list[dict] | None = None, scheduled_at: str | None = None) -> dict: ...
    @abstractmethod
    async def get_scheduled_posts(self, profile_id: str) -> list[dict]: ...


class ImageGenClientBase(BaseIntegrationClient):
    @abstractmethod
    async def generate_image(self, prompt: str, style: str = "digital-art", size: str = "1024x1024") -> dict: ...


class TrendsClientBase(BaseIntegrationClient):
    @abstractmethod
    async def get_interest_by_region(self, keywords: list[str], geo: str = "", timeframe: str = "today 12-m") -> dict: ...
    @abstractmethod
    async def get_interest_over_time(self, keywords: list[str], geo: str = "", timeframe: str = "today 12-m") -> dict: ...
