from app.routers import (
    academy,
    analytics,
    campaigns,
    champions_league,
    channel_audit,
    competitors,
    content,
    diaspora,
    engagement,
    fans,
    market_research,
    optimization,
    reports,
    sentiment,
    settings,
    social_listening,
)

__all__ = [
    "academy",
    "analytics",
    "campaigns",
    "champions_league",
    "channel_audit",
    "competitors",
    "content",
    "diaspora",
    "engagement",
    "fans",
    "market_research",
    "optimization",
    "reports",
    "sentiment",
    "settings",
    "social_listening",
]
